### ISSUE TITLE
Implement cutsets UI in fault tree editor

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#169]
```[tasklist]
### Tasks
- [ ] https://github.com/kbss-cvut/fta-fmea-ui/issues/170
- [ ] https://github.com/kbss-cvut/fta-fmea-ui/issues/195
- [ ] https://github.com/kbss-cvut/fta-fmea-ui/issues/171
```

**Comment by Kasmadei** [comment]
Closing as all subtasks are closed.
