### ISSUE TITLE
Fix issues fault event node editor

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#432]
```[tasklist]
### Tasks
- [ ] https://github.com/kbss-cvut/fta-fmea-ui/issues/417
- [ ] https://github.com/kbss-cvut/fta-fmea-ui/issues/433
- [ ] https://github.com/kbss-cvut/fta-fmea-ui/issues/435
```

**Comment by blcham** [comment]
I think this ticket is not that informative -- it is just high-level aggregation of subtasks. I am closing this issue while moving subtask to "Next" sprint.
