### ISSUE TITLE
User can't use operational failure rate if it is missing in the data

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#525]
Operational failure rate cannot be used if it is not present in the data. 

![Image](https://github.com/user-attachments/assets/78db58bb-6b1f-4b8b-aa71-e1382b3bf6a9)

Tasks:
- [x] Open access to failure rate api in analytics server module - resolved in kbss-cvut/ava-analytics#39 
- [ ] Fix SNS export - add general fault event types (not related to aircraft) kbss-cvut/23ava-distribution#129
- [x] kbss-cvut/fta-fmea-ui#533

**Comment by blcham** [comment]
Currently this was done by workaround -- https://github.com/kbss-cvut/ava-analytics/pull/39, but should be properly fixed later.

**Comment by blcham** [comment]
@kostobog so does it work now ?

**Comment by kostobog** [comment]
@blcham 
This works. User can user operational failure rate if it is not calculated yet. 

First user has to click the tree evaluation button.  Operational failure rates in the tree will be updated according to the value of `min. operational hours` field next to the button even if there is an error message that the tree could not be evaluate due to unspecified failure rates in some of of the leaf nodes. 

To see the newly added operational failure rates in the SNS node the tree must reloaded. The tree could be reloaded in several ways:
1. automatically if the tree was evaluated successfully without error messages for missing failure rates in leaf nodes
2. by updating one of the nodes, e.g. change the name of change the failure rate selection or manual failure rate. 
3. exit the tree and open it again

**Comment by blcham** [comment]
@kostobog ok I guess the workaround you mentioned is good enough as it is, what do you think? 
If so i suggest to close this issue.

**Comment by kostobog** [comment]
@blcham 
Open access workaround works but I am not sure if we want keep it?

Otherwise, I can improve user experience by reloading the tree even if there were missing failure rates at the leaf events. This way the user will always need to only click the evaluate button to see the missing operational failure rates.

**Comment by blcham** [comment]
If it does not introduce other issues it would be better UX if you reload.

**Comment by blcham** [comment]
So we can close this issue if:
- [ ] refresh of failed evaluation works
- [ ] if the ticket about securing ava-analytics contains also adaptation of 23-ava
